### ISSUE TITLE
Build fails with webpacker 3.3.0

### ISSUE THREAD

**Issue by brian-kephart** [heroku/heroku-buildpack-ruby#715]
After upgrading from webpacker 3.2.2 to 3.3.0, I get this error and the build fails.

```
[4/4] Building fresh packages...
remote:        Done in 20.95s.
remote:        Webpacker is installed 🎉 🍰
remote:        Using /tmp/build_57339fdd6d174011077ddb778d8e112f/config/webpacker.yml file for setting up webpack paths
remote:        Compiling…
remote:        Compilation failed:
remote:        /tmp/build_57339fdd6d174011077ddb778d8e112f/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/rubygems_integration.rb:432:in `block in replace_bin_path': can't find executable webpack for gem webpacker (Gem::Exception)
remote:        from /tmp/build_57339fdd6d174011077ddb778d8e112f/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/rubygems_integration.rb:463:in `block in replace_bin_path'
remote:        from ./bin/webpack:29:in `<main>'
remote:  !
remote:  !     Precompiling assets failed.
```

~~There are no issues running the app locally~~, and an identical build with 3.2.2 succeeds on Heroku. **EDIT: It appears I had compiled assets masking the problem when running locally. This appears to be a webpacker problem. Sorry for the false alarm.**

I ran both `bundle update webpacker` and `yarn upgrade @rails/webpacker --latest` before deploying.

Given that some similar issues have been solved by inserting the Node buildpack before the Ruby buildpack, I tried that. Result was the same, build failed in the same place.

Incidentally, both buildpacks installed the yarn dependencies from scratch, but that seems like a separate issue.
